//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Framework.Entities //add
{
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string Content { get; set; }
        public string PostID { get; set; }
    
        public virtual Post Posts { get; set; }
    }
    
}
