//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Framework.Entities //add
{
    public partial class UserExtra
    {
        public int UserID { get; set; }
        public string LastIP { get; set; }
        public System.DateTime LsatDate { get; set; }
    
        public virtual Users User { get; set; }
    }
    
}
