//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Framework.Entities //add
{
    public partial class Users
    {
        public Users()
        {
            this.IsAdmin = false;
            this.Posts = new HashSet<Post>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Passowrd { get; set; }
        public bool IsAdmin { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual UserExtra UserExtras { get; set; }
    }
    
}
